# Generated by Django 3.2.4 on 2023-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyberbullying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.TextField()),
                ('cyberbullying', models.CharField(max_length=500)),
            ],
        ),
    ]
