# Generated by Django 3.0.4 on 2024-06-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyberbullying',
            old_name='cyberbullying',
            new_name='cyber_data',
        ),
        migrations.AlterField(
            model_name='cyberbullying',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
