# Generated by Django 3.0.4 on 2024-06-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20240607_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cyberbullying',
            new_name='CyberTweets',
        ),
    ]
