# Generated by Django 6.0.6 on 2026-06-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20240607_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybertweets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
